<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Application\Common\Exceptions\" />
    <Folder Include="Application\Common\Interfaces\" />
    <Folder Include="Application\Common\Mappings\" />
    <Folder Include="Application\Common\Models\" />
    <Folder Include="Application\Common\Security\" />
    <Folder Include="Application\Resources\" />
    <Folder Include="Domain\Constants\" />
    <Folder Include="Domain\Entities\" />
    <Folder Include="Domain\Enums\" />
    <Folder Include="Domain\ValueObjects\" />
    <Folder Include="Infrastructure\Adapters\" />
    <Folder Include="Infrastructure\Data\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="3.10.0" />
    <PackageReference Include="Google.Cloud.PubSub.V1" Version="3.24.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
